---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: examples
spec:
  owner: guests
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-website
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples
  providesApis: [example-grpc-api]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: example-grpc-api
spec:
  type: grpc
  lifecycle: experimental
  owner: guests
  system: examples
  definition: |
    syntax = "proto3";

    service Exampler {
      rpc Example (ExampleMessage) returns (ExampleMessage) {};
    }

    message ExampleMessage {
      string example = 1;
    };
---
# Example catalog-info.yaml entity definition file
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Xalt-Cloudlink-API
  description: Xalt CloudLink API Repo Azure
  system: Xalt Configuration
  annotations:
    dev.azure.com/project-repo: "Xalt Configuration/Xalt-CloudLink-API"
    #dev.azure.com/readme-path: README.md
    backstage.io/techdocs-ref: dir:.
    dev.azure.com/host-org: dev.azure.com/HexagonXalt
spec:
  type: service
  lifecycle: experimental
  owner: guests
---
# Example add devops project
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Xalt-DevOps
  title: "Xalt Devops"
  description: Xalt Pipeline Template Repo Azure
  system: Xalt-DevOps
  tags:
    - CNGDevops
    - PipelineTemplate
  links:
    - url: https://dev.azure.com/HexagonXalt/Xalt%20DevOps/_boards/board/t/Xalt%20Cloud%20Native%20team/Stories
      title: Project board  
      icon: dashboard   
      type: admin-dashboard
  annotations:
    backstage.io/source-location: url:https://dev.azure.com/HexagonXalt/Xalt%20DevOps/_git/xalt-azure-pipeline-templates
    dev.azure.com/project-repo: "Xalt DevOps/xalt-azure-pipeline-templates"
    #dev.azure.com/readme-path: https://dev.azure.com/javedfaruquee0654/_git/javedfaruquee?path=/README.md&version=GBmain&_a=contents
    backstage.io/techdocs-ref: dir:.
    dev.azure.com/host-org: dev.azure.com/HexagonXalt
spec:
  type: service
  lifecycle: deployment
  owner: guests
---
# Example different organization
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: My-Organization
  description: My Azure Organization
  system: Self 
  annotations:
    dev.azure.com/project-repo: "javedfaruquee/javedfaruquee"
    #dev.azure.com/readme-path: README.md
    backstage.io/techdocs-ref: dir:.
    dev.azure.com/host-org: dev.azure.com/javedfaruquee0654
spec:
  type: service
  lifecycle: experimental
  owner: guests